// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
	    
		int sumOfGreater =0;
		int sumOfSmaller = 0;
		double randomNumber = 0;
		int n = Integer.parseInt("" + args[0]);
		System.out.println(n);
		for (int i=0; i<=n; i++)
		{
			randomNumber = Math.random();
			if (randomNumber>0.5)
				sumOfGreater = sumOfGreater+1;
			else
				sumOfSmaller = sumOfSmaller+1;
		}

		System.out.println("> 0.5: " + sumOfGreater +" times");
		System.out.println("<= 0.5: " + sumOfSmaller +" times");
	}
}
